baseURL = "https://keyofsamuel.com/"
languageCode = "en-us"
title = "Technology and Music"
theme = "coffeecup"

relativeURLs = true
summaryLength = 30

[menu]
  [[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about"
    weight = 2
  [[menu.main]]
    identifier = "technology"
    name = "TECHNOLOGY PORTFOLIO"
    url = "/portfolio/technology"
    weight = 3
  [[menu.main]]
    identifier = "music"
    name = "MUSIC PORTFOLIO"
    url = "/portfolio/music"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "RAMBLING BLOG"
    url = "/posts"
    weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
    
# Site Params
[params]
#titleImage = "images/icon.png"
subtitle = "Technology. Music. And everything between."
fontawesome = "https://kit.fontawesome.com/dc511c6fde.js"
image = "/images/cassette-markus_spiske-unsplash-600.jpg"
blogtitle = "Ramblings between..."

# Hero Section
[params.hero]
image = "/images/cassette-markus_spiske-unsplash-600.jpg"
credit = "Markus Spiske on Unsplash"
heading = "Samuel A. Campbell"
subheading = "Technology. Music. And everything between."
description = "My life, at least the part that would interest anybody, is technology and music. Here I’ll document my journeys and projects. Someone may find it interesting..."

# Footer Section
[params.footer]
name = "Samuel A. Campbell"
description = "Technology. Music. And everything between."
location = "Pittsburgh, PA"
locationicon = "fas fa-map-marker-alt"

[[params.footer.links]]
name = "EMAIL"
icon = "far fa-envelope"
url = "mailto://keyofsamuel@gmail.com"

[[params.footer.links]]
name = "WEBSITE"
icon = "fas fa-globe"
url = "https://keyofsamuel.github.io"

[[params.footer.links]]
name = "FACEBOOK"
icon = "fab fa-facebook"
url = "https://fb.me/nytewyyrm"

[[params.footer.links]]
name = "GITHUB"
icon = "fab fa-github"
url = "https://github.com/KeyofSamuel"

[[params.footer.links]]
name = "LINKEDIN"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/samuel-campbell-8829b6113/"
